=== Shubhi66302/mapcreator/server/src/json-schemas/fire_emergency.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "fire_emergency",
  "title": "Fire Emergency schema",
  "type": "object",
  "required": ["priority", "type", "group_id", "barcode"],
  "properties": {
    "priority": { "type": "string", "enum": ["0", "1"] },
    "type": { "type": "string", "enum": ["escape_path", "shutter"] },
    "group_id": { "type": "string" },
    "barcode": { "$ref": "definitions#/barcodeString" }
  }
}

=== Shubhi66302/mapcreator/server/test/json-schemas/test-jsons/maps/3-7/fire_emergency.json
[
  {
    "group_id": "1",
    "barcode": "017.018",
    "type": "escape_path",
    "priority": "1"
  },
  {
    "group_id": "1",
    "barcode": "017.017",
    "type": "escape_path",
    "priority": "1"
  },
  {
    "group_id": "1",
    "barcode": "018.018",
    "type": "escape_path",
    "priority": "1"
  },
  {
    "group_id": "1",
    "barcode": "018.017",
    "type": "escape_path",
    "priority": "1"
  },
  { "group_id": "2", "barcode": "017.015", "type": "shutter", "priority": "0" },
  { "group_id": "2", "barcode": "018.015", "type": "shutter", "priority": "0" }
]
