=== Shubhi66302/mapcreator/client/src/common/json-schemas/elevator.json
{
  "$schema": "http://json-schema.org/schema#",

  "localdefs": {
    "entryExitBarcodesSchema": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["barcode", "floor_id", "boom_barrier_id"],
        "properties": {
          "barcode": { "$ref": "definitions#/barcodeString" },
          "floor_id": { "type": "integer", "minimum": 1 },
          "boom_barrier_id": { "type": "integer", "minimum": 1 }
        }
      }
    }
  },

  "$id": "elevator",
  "title": "elevator schema",
  "type": "object",
  "required": [
    "coordinate_list",
    "type",
    "entry_barcodes",
    "exit_barcodes",
    "elevator_id",
    "position"
  ],
  "additionalProperties": false,
  "properties": {
    "coordinate_list": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["direction", "coordinate"],
        "properties": {
          "direction": { "$ref": "definitions#/direction" },
          "coordinate": { "$ref": "definitions#/coordinate" }
        }
      }
    },
    "type": { "type": "string", "enum": ["c_type", "z_type"] },
    "entry_barcodes": { "$ref": "#/localdefs/entryExitBarcodesSchema" },
    "exit_barcodes": { "$ref": "#/localdefs/entryExitBarcodesSchema" },
    "elevator_id": { "type": "integer" },
    "position": { "$ref": "definitions#/barcodeString" },
    "reinit_barcodes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["barcodes", "floor_id"],
        "properties": {
          "barcodes": {
            "type": "array",
            "items": { "$ref": "definitions#/barcodeString" }
          },
          "floor_id": { "type": "integer" }
        }
      }
    }
  }
}

=== Shubhi66302/mapcreator/server/test/json-schemas/test-jsons/good-elevators.json
[
  {
    "entry_barcodes": [
      { "barcode": "015.019", "floor_id": 1, "boom_barrier_id": 1 },
      { "barcode": "048.049", "floor_id": 2, "boom_barrier_id": 1 },
      { "barcode": "017.011", "floor_id": 1, "boom_barrier_id": 2 }
    ],
    "coordinate_list": [
      { "coordinate": [19, 16], "direction": 2 },
      { "coordinate": [19, 16], "direction": 2 },
      { "coordinate": [49, 47], "direction": 2 },
      { "coordinate": [49, 47], "direction": 2 },
      { "coordinate": [49, 47], "direction": 2 }
    ],
    "type": "c_type",
    "position": "016.019",
    "reinit_barcodes": [
      { "barcodes": ["016.020"], "floor_id": 1 },
      { "barcodes": [], "floor_id": 2 }
    ],
    "elevator_id": 1,
    "exit_barcodes": [
      { "barcode": "017.019", "floor_id": 1, "boom_barrier_id": 3 },
      { "barcode": "047.048", "floor_id": 2, "boom_barrier_id": 4 }
    ]
  },
  {
    "entry_barcodes": [
      { "barcode": "012.012", "floor_id": 1, "boom_barrier_id": 1 },
      { "barcode": "042.042", "floor_id": 2, "boom_barrier_id": 1 }
    ],
    "coordinate_list": [
      { "coordinate": [11, 12], "direction": 2 },
      { "coordinate": [11, 12], "direction": 2 },
      { "coordinate": [41, 42], "direction": 2 },
      { "coordinate": [41, 42], "direction": 2 },
      { "coordinate": [41, 42], "direction": 2 }
    ],
    "type": "c_type",
    "position": "012.011",
    "reinit_barcodes": [
      { "barcodes": [], "floor_id": 1 },
      { "barcodes": [], "floor_id": 2 }
    ],
    "elevator_id": 2,
    "exit_barcodes": [
      { "barcode": "012.010", "floor_id": 1, "boom_barrier_id": 2 },
      { "barcode": "042.040", "floor_id": 2, "boom_barrier_id": 3 }
    ]
  }
]
